using BitcoinAgent.Application.Interfaces;
using BitcoinAgent.Application.Validators;
using BitcoinAgent.Domain.Models;

namespace BitcoinAgent.Application.Middleware;

/// <summary>
/// Validates the final response generated by the LLM before it is returned to the user.
/// </summary>
public sealed class LLMResponseValidationMiddleware : IOrderedMiddleware
{
    private readonly LlmResponseValidator _validator;
    private readonly ILogger<LLMResponseValidationMiddleware> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="LLMResponseValidationMiddleware"/> class.
    /// </summary>
    /// <param name="validator">The validator.</param>
    /// <param name="logger">The logger.</param>
    public LLMResponseValidationMiddleware(
        LlmResponseValidator validator,
        ILogger<LLMResponseValidationMiddleware> logger)
    {
        this._validator = validator;
        this._logger = logger;
    }

    public int Order => (int)MiddlewareOrder.LlmResponseValidation;

    /// <summary>
    /// Invokes the middleware to validate the final response generated by the LLM before it is returned to the user.
    /// </summary>
    /// <param name="context">The agent context.</param>
    /// <param name="next">The next delegate in the pipeline.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    public async Task InvokeAsync(
        AgentContext context,
        AgentDelegate next,
        CancellationToken cancellationToken)
    {
        await next(context, cancellationToken);

        var response = context.Response;

        this._logger.LogDebug(
            "LLM response before validation (length: {Length}).",
            response?.Length ?? 0);

        /*
         * Empty response is a retryable failure.
         * Do not throw exception here.
         */
        if (string.IsNullOrWhiteSpace(response))
        {
            const string error = "LLM returned empty response.";

            this._logger.LogWarning("{Error}.",error);

            RequestRetry(context, error);

            return;
        }

        // Normalize the response before validation.
        var normalized = response.Trim();

        var validation = this._validator.Validate(normalized);

        if (validation.IsValid)
        {
            context.Response = normalized;

            this._logger.LogDebug("LLM response validation succeeded.");

            return;
        }

        foreach (var error in validation.Errors)
        {
            this._logger.LogWarning(
                "LLM response validation failed: {Error}.",error);
        }

        RequestRetry(context, string.Join("; ", validation.Errors));
    }

    /// <summary>
    /// Marks the current response as retryable and clears the response.
    /// </summary>
    /// <param name="context">The agent context.</param>
    /// <param name="reason">The retry reason.</param>
    private static void RequestRetry(
        AgentContext context,
        string reason)
    {
        context.Items[AgentContextKeys.RetryRequired] = true;
        context.Items[AgentContextKeys.RetryReason] = reason;
        context.Response = null;
    }
}