namespace BitcoinAgent.Application.Validators;

/// <summary>
/// Validates the final response generated by the LLM.
/// </summary>
public sealed class LlmResponseValidator
{
    private static readonly string[] ForbiddenPhrases =
    [
        "ignore previous instructions",
        "system prompt",
        "internal policy"
    ];

    /// <summary>
    /// Validates the final response generated by the LLM.
    /// </summary>
    /// <param name="response">The response to validate.</param>
    /// <returns>The validation result.</returns>
    public ValidationResult Validate(string? response)
    {
        var errors = new List<string>();

        if (string.IsNullOrWhiteSpace(response))
        {
            errors.Add("LLM returned an empty response.");
        }

        if (!string.IsNullOrWhiteSpace(response) && response.Length < 4)
        {
            errors.Add("LLM response is too short.");
        }

        foreach (var phrase in ForbiddenPhrases)
        {
            if (!string.IsNullOrWhiteSpace(response) && response.Contains(phrase, StringComparison.OrdinalIgnoreCase))
            {
                return ValidationResult.Failed(["LLM response contains forbidden content."]);
            }
        }

        return errors.Count == 0
            ? ValidationResult.Success()
            : ValidationResult.Failed(errors);
    }
}